### ISSUE TITLE
`surfaceflinger` and `system_server` `getattr` denied log spam

### ISSUE THREAD

**Issue by zenfyrdev** [realahnet/treble_evo#7]
There appear to be some missing SELinux rules. Currently, I work around this using `magiskpolicy` and this command:

```sh
magiskpolicy --live "allow { surfaceflinger } * { process } { getattr }"
magiskpolicy --live "allow { system_server } * { process } { getattr }"
```

I'm not sure if this affects functionality in any way, just slightly annoying while reading logs :)

**Comment by realahnet** [comment]
if it aint broke dont fix it :)
