### ISSUE TITLE
[REQUEST] a/b ab 64, binder-64, ARM32

### ISSUE THREAD

**Issue by LinggaCR17** [realahnet/treble_evo#8]
vanilla only (no gapps), rw partition only.. can it be agreed?

I'll tested for it

**Comment by realahnet** [comment]
Vanilla only  - Never. Evolution-X is designed with pixel experince in mind
RW - too big for most users (4.5-5GB)

binder64/arm32- Pixel gapps wont work. 


Hence closing the issue
